spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true # sql 문 보여주기 , 하지만 로그로 보는것이 바람직
        format_sql: true

  # 페이징에 관한 글로벌 설정
  data:
    web:
      pageable:
        default-page-size: 10 # 기본 페이지 사이즈
        max-page-size: 2000 # 최대 페이지 사이즈
        #one-indexed-parameters: true # 시작 페이지를 1로 , 하지만 한계가 있어 비추천

logging.level:
  org.hibernate.SQL: debug # sql로그로 기록 보기
# org.hibernate.type: trace # sql문 적확이 볼 수 잇지만 보기 편한 다른 라이브러리 이용함